Multiplatform migration
dimagor555/password-manager-android pull request #2
Opened 2022-11-02 17:50 UTC by dromanryuk

2022-11-02 21:55 UTC, dimagor555 requested changes
жду ответов и правок по комметариям

2022-11-02 21:55 UTC, dimagor555 commented on core/build.gradle.kts
> +        val androidMain by getting {
стоит удалить эти пустые блоки, их можно добавить потом если это будет необходимо

2022-11-02 21:55 UTC, dimagor555 commented on core/build.gradle.kts
> +    compileSdk = 33
здесь следует использовать версии из конфиг файла Android.kt из buildSrc, а не хардкодить

2022-11-02 21:55 UTC, dimagor555 commented on encryption-core/build.gradle.kts
> +        val desktopMain by getting {
пустые блоки следует удалять

2022-11-02 21:55 UTC, dimagor555 commented on encryption-core/build.gradle.kts
> +    compileSdk = 33
версии не следует хардкодить

2022-11-02 21:55 UTC, dimagor555 commented on master-password-feature/build.gradle.kts
> +group = "ru.dimagor555.masterpassword"
group и version не нужны для модулей, которые будут использоваться только в этом проекте, т.е. не будут подключаться как библитеку к другим проектам

2022-11-02 21:55 UTC, dimagor555 commented on master-password-feature/build.gradle.kts
> +    compileSdk = 33
версии не следует хардкодить

2022-11-02 21:55 UTC, dimagor555 commented on master-password-feature/src/commonMain/kotlin/ru.dimagor555.masterpassword/ui/di/PasswordUiModule.kt
> +val masterPasswordUiModule = module {
не понятно почему модуль содержит в названии UI? как он связан с UI? в нём же только юзкейсы

2022-11-02 21:55 UTC, dimagor555 commented on master-password-feature/src/commonMain/kotlin/ru.dimagor555.masterpassword/ui/editscreen/EditMasterPasswordComponent.kt
> +sealed interface EditMasterPasswordComponent {
что-то не понял зачем здесь sealed

2022-11-02 21:55 UTC, dimagor555 commented on master-password-feature/src/commonMain/kotlin/ru.dimagor555.masterpassword/ui/loginscreen/LoginComponent.kt
> +sealed interface LoginComponent
тоже не понял, зачем здесь sealed?

2022-11-02 21:55 UTC, dimagor555 commented on master-password-feature/src/commonMain/kotlin/ru.dimagor555.masterpassword/ui/startscreen/WelcomeComponentImpl.kt
> +
некрасивая лишняя пустая строка

2022-11-02 21:55 UTC, dimagor555 commented on master-password-feature/src/commonMain/kotlin/ru.dimagor555.masterpassword/ui/startscreen/WelcomeScreen.kt
> +    WelcomeSurface { component.navigateNext() }
передавать последнюю лямбду в фигурных скобках нормально в компоузе, если в ней UI контент
здесь же действие и не понятно какое, поэтому лучше передавать в круглых скобках с именами аргументов

2022-11-02 21:55 UTC, dimagor555 commented on master-password-feature/src/desktopMain/kotlin/ru/dimagor555/masterpassword/ui/loginscreen/biometric/BiometricLoginDialog.kt
> +) {
можно писать `= Unit` вместо пустых скобок, ну и пустые скобки лучше писать на одной строке вот так `{ }`

2022-11-02 21:55 UTC, dimagor555 commented on master-password-feature/src/desktopMain/kotlin/ru/dimagor555/masterpassword/ui/loginscreen/biometric/OnCanUseBiometricLogin.kt
> +internal actual fun OnCanUseBiometricLogin(action: () -> Unit) {
здесь тоже было бы неплохо написать просто `= Unit`

2022-11-02 21:55 UTC, dimagor555 commented on password-feature/src/commonMain/kotlin/ru.dimagor555.password/ui/createscreen/CreatePasswordComponentImpl.kt
> +        if (sideEffect is CommonEditPasswordStore.SideEffect.ValidationSucceed)
`if`следует писать с фигурными скобочками для лучшей читаемости

2022-11-02 21:55 UTC, dimagor555 commented on password-feature/src/commonMain/kotlin/ru.dimagor555.password/ui/di/PasswordUiModule.kt
> +//    viewModelOf(::PasswordDetailsViewModel)
следует удалить мёртвый код

2022-11-02 21:55 UTC, dimagor555 commented on password-generation-feature/src/commonMain/kotlin/ru.dimagor555.passwordgeneration/ui/screen/PasswordGenerationComponent.kt
> +
лишняя пустая строка

2022-11-02 21:55 UTC, dimagor555 commented on password-generation-feature/src/commonMain/kotlin/ru.dimagor555.passwordgeneration/ui/screen/PasswordGenerationComponentImpl.kt
> +
лишняя пустая строка

2022-11-02 21:55 UTC, dimagor555 commented on root/src/commonMain/kotlin/ru/dimagor555/core/presentation/PasswordManagerRootComponent.kt
> +    private val componentScope by this.componentScope()
`this` здесь лишний

2022-11-02 21:55 UTC, dimagor555 commented on root/src/commonMain/kotlin/ru/dimagor555/core/presentation/PasswordManagerRootComponent.kt
> +    private val generatedPassword = MutableSharedFlow<GeneratedPassword>(
все поля следует объявлять до блока `init`

2022-11-02 21:55 UTC, dimagor555 commented on root/src/commonMain/kotlin/ru/dimagor555/core/presentation/PasswordManagerRootComponent.kt
> +    private fun determineStartDestination(): Config = runBlocking {
этот метод вызывается самым первым, а расположен в самом конце
нарушен порядок объявления методов
его следует объявить в самом начале секции методов

2022-11-02 21:55 UTC, dimagor555 commented on root/src/commonMain/kotlin/ru/dimagor555/core/presentation/PasswordManagerRootComponent.kt
> +    private fun List<RootComponent.Child>.sendChildrenGeneratedPassword(password: String) {
немного странное название метода, я бы назвал `sendGeneratedPasswordToChildren`

2022-11-02 21:55 UTC, dimagor555 commented on root/src/commonMain/kotlin/ru/dimagor555/core/presentation/PasswordManagerRootComponent.kt
> +            if (password != null) {
здесь лучше не создавать новые уровни вложенности и не использовать многострочный `if`
вместо этого лучше дописать на 99 строке `?: return@collect`

2022-11-02 21:55 UTC, dimagor555 commented on root/src/commonMain/kotlin/ru/dimagor555/core/presentation/model/Config.kt
> +    @Parcelize
по нашему стилю кода сверху класса следует оставлять пустую стороку

2022-11-02 21:55 UTC, dimagor555 commented on root/src/commonMain/kotlin/ru/dimagor555/core/presentation/model/Config.kt
> +
по нашему стилю кода вот таких пустых строк перед концом класса не должно быть

2022-11-27 12:04 UTC, dimagor555 commented
Посмотрел часть фиксов и закрыл треды, жду исправления остальных

2022-11-27 13:07 UTC, dromanryuk commented on master-password-feature/src/commonMain/kotlin/ru.dimagor555.masterpassword/ui/di/PasswordUiModule.kt
> +val masterPasswordUiModule = module {
Изменил название на masterPasswordModule

2022-11-27 13:23 UTC, dromanryuk commented on master-password-feature/src/commonMain/kotlin/ru.dimagor555.masterpassword/ui/editscreen/EditMasterPasswordComponent.kt
> +sealed interface EditMasterPasswordComponent {
Удалил sealed со всех интерфейсов компонентов

2022-11-27 13:23 UTC, dromanryuk commented on master-password-feature/src/commonMain/kotlin/ru.dimagor555.masterpassword/ui/startscreen/WelcomeComponentImpl.kt
> +
Удалил строку

2022-11-27 13:30 UTC, dromanryuk commented on master-password-feature/src/commonMain/kotlin/ru.dimagor555.masterpassword/ui/startscreen/WelcomeScreen.kt
> +    WelcomeSurface { component.navigateNext() }
Переписал вызов с использованием именованного аргумента

2022-11-27 13:37 UTC, dromanryuk commented on master-password-feature/src/desktopMain/kotlin/ru/dimagor555/masterpassword/ui/loginscreen/biometric/BiometricLoginDialog.kt
> +) {
Исправил

2022-11-27 13:37 UTC, dromanryuk commented on master-password-feature/src/desktopMain/kotlin/ru/dimagor555/masterpassword/ui/loginscreen/biometric/OnCanUseBiometricLogin.kt
> +internal actual fun OnCanUseBiometricLogin(action: () -> Unit) {
Исправил

2022-11-27 13:41 UTC, dromanryuk commented on password-feature/src/commonMain/kotlin/ru.dimagor555.password/ui/createscreen/CreatePasswordComponentImpl.kt
> +        if (sideEffect is CommonEditPasswordStore.SideEffect.ValidationSucceed)
Исправил

2022-11-27 13:46 UTC, dromanryuk commented on password-feature/src/commonMain/kotlin/ru.dimagor555.password/ui/di/PasswordUiModule.kt
> +//    viewModelOf(::PasswordDetailsViewModel)
Исправил

2022-11-27 13:47 UTC, dromanryuk commented on password-generation-feature/src/commonMain/kotlin/ru.dimagor555.passwordgeneration/ui/screen/PasswordGenerationComponent.kt
> +
Исправил

2022-11-27 13:48 UTC, dromanryuk commented on password-generation-feature/src/commonMain/kotlin/ru.dimagor555.passwordgeneration/ui/screen/PasswordGenerationComponentImpl.kt
> +
Исправил

2022-11-27 13:54 UTC, dromanryuk commented on root/src/commonMain/kotlin/ru/dimagor555/core/presentation/PasswordManagerRootComponent.kt
> +    private val componentScope by this.componentScope()
Удалил

2022-11-27 13:54 UTC, dromanryuk commented on root/src/commonMain/kotlin/ru/dimagor555/core/presentation/PasswordManagerRootComponent.kt
> +    private val generatedPassword = MutableSharedFlow<GeneratedPassword>(
Перенёс поле до блока init

2022-11-27 14:14 UTC, dimagor555 approved these changes
Ну вроде всё исправлено, можно мержить

2022-11-27 14:15 UTC, merged